import { Router } from 'express';
import auth from '../auth';
import dashboard from '../dashboard';
import customers from '../customers';
import drivers from '../drivers';
import rides from '../rides';
import attendance from '../attendance';
import invoices from '../invoices';
import settings from '../settings';
import notices from './notices';
import faqs from './faqs';
import inquiries from './inquiries';
import complaints from './complaints';
import withdrawals from './withdrawals';
import coupons from './coupons';
import couponRequests from './couponRequests';
import users from './users';
import appInstall from './appInstall';
import referrals from './referrals';
import me from './me';
import counselors from './counselors';
import appAccess from './appAccess';
import appImages from './appImages';
import usageGuide from './usageGuide';
import ads from './ads';
import mileage from './mileage';
import cardPayments from './cardPayments';
import sms from './sms';
import appInstallStats from './appInstallStats';
import orderStats from './orderStats';
import numberChange from './numberChange';
import recommendationKings from './recommendationKings';
import storage from './storage';
import uploads from './uploads';
import { authMiddleware } from '../../middleware/auth';

const router = Router();

router.use('/auth', auth);
router.use(authMiddleware);
router.use('/me', me);
router.use('/dashboard', dashboard);
router.use('/customers', customers);
router.use('/drivers', drivers);
router.use('/rides', rides);
router.use('/attendance', attendance);
router.use('/invoices', invoices);
router.use('/settings', settings);
router.use('/notices', notices);
router.use('/faqs', faqs);
router.use('/inquiries', inquiries);
router.use('/complaints', complaints);
router.use('/withdrawals', withdrawals);
router.use('/coupons', coupons);
router.use('/coupon-requests', couponRequests);
router.use('/app-install', appInstall); // GET 목록, DELETE /referrer
router.use('/app-install-stats', appInstallStats);
router.use('/order-stats', orderStats);
router.use('/number-change', numberChange);
router.use('/recommendation-kings', recommendationKings);
router.use('/users', users);
router.use('/referrals', referrals);
router.use('/counselors', counselors);
router.use('/app-access', appAccess);
router.use('/app-images', appImages);
router.use('/usage-guide', usageGuide);
router.use('/ads', ads);
router.use('/mileage', mileage);
router.use('/card-payments', cardPayments);
router.use('/sms', sms);
router.use('/storage', storage);
router.use('/uploads', uploads);

export default router;
